### ISSUE TITLE
[1.1.0] Date Selector on planning missing

### ISSUE THREAD

**Issue by M-Falken** [ticgal/taskdrop#2]
Hi

GLPI 9.3.3

When the plugin is activated, we missing both the calendar date selector and refresh icon on the planning.
No backtrace log, no error in console.
Normal behaviour ?
Regards,

![screenshot-2019 01 31-15-11-41](https://user-images.githubusercontent.com/1380639/52059799-09f09180-256b-11e9-9ffd-915035484ef3.png)

**Comment by Gwenaelle93** [comment]
I have the same problem. Will this soon be corrected?

Best regards

**Comment by OscarBeiro** [comment]
Hi @Gwenaelle93.
Thanks for using Task'n'drop :)

**Quick answer:**
Probably not

**Not so quick answer:**
Apparently the soon to be released GLPI 9.5, will have a feature that will integrate this functionality, rendering  this plugin obsolete.
It makes no sense investing time fixing something that will be deprecated soon.

But if the announced functionality doesn't work as expected, it could be done.

Regards.

**Comment by Gwenaelle93** [comment]
thank you for your reply.
Regards.

**Comment by xacobofg** [comment]
Solved #4
