### ISSUE TITLE
Error when selecting all users of a group

### ISSUE THREAD

**Issue by OscarBeiro** [ticgal/taskdrop#5]
<p><a href="https://github.com/ticgal/taskdrop/issues/5">https://github.com/ticgal/taskdrop/issues/5</a></p><p>If <strong>All users of a group</strong> is chosen, a PHP error is generated. <code>PHP Notice (8): Undefined index: color in /usr/share/glpi/marketplace/taskdrop/inc/calendar.class.php at line 77</code></p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_6955' rel='nofollow'>6955</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by inesmv** [comment]
Issue: https://github.com/glpi-project/glpi/issues/12334
