### ISSUE TITLE
Dragging task that extends beyond calendar view will truncate task end date.

### ISSUE THREAD

**Issue by derry43** [ticgal/taskdrop#6]
<p><a href="https://github.com/ticgal/taskdrop/issues/6">https://github.com/ticgal/taskdrop/issues/6</a></p><p>Dragging project task which extends beyond calendar view truncates the end date (time) to last day in visible view.</p><p>This can be demonstrated as follows:</p><p>Create a task (Task A) which starts at 11:00 AM on Wed 13th Oct 2021 and finishes at 08:00 AM on Friday 15th Oct 2021 (same week).</p><p>Assign Task A to yourself (or in Project Task add yourself to Project Task Team).</p><p>Open Planning -> Month view.</p><p>Drag Task A from 11:00 AM on 13th Oct to 10:00 AM on 13 Oct and dates/times change correctly.</p><p>Change to Planning -> Week view.</p><p>Before Task Move <img src="https://user-images.githubusercontent.com/47180698/136198471-73afd7a7-983a-4f53-9889-fad971c8b908.png" alt="week-before" /></p><p>Drag Task A from 11:00 AM on 13th Oct to 10:00 AM on 13 Oct and dates/times change correctly. Start and finish times show correctly on calendar task before and after.</p><p>After Task Move <img src="https://user-images.githubusercontent.com/47180698/136198533-84dc3a9e-f166-44c1-bebe-9e4a55c07bb3.png" alt="week-after" /></p><p>Change to Planning -> Day view</p><p>Before Task Move (end time is incorrect now) <img src="https://user-images.githubusercontent.com/47180698/136199022-8dd46e90-2d51-475c-bcc0-2e67129d44d7.png" alt="day-before" /></p><p>The part of the task which extends onto the date of 13th Oct is show in the lower part of the calendar view. The part of the task which is on 14th is shown in the all-day section</p><p>Drag Task A from 11:00 AM on 13th Oct to 10:00 AM on 13 Oct and dates/times change <strong>incorrectly</strong>. Appears as though task is truncated to end of visible day.</p><p><img src="https://user-images.githubusercontent.com/47180698/136198577-21ce595a-413f-4c3d-b308-2e1c1065dae2.png" alt="day-after" /></p><p>This can also be seen in task detail.</p><p><img src="https://user-images.githubusercontent.com/47180698/136199110-23d98597-a751-4299-bb0e-86f41a983ac9.png" alt="dates-after" /></p><p>Same thing happens on Week view if task extends beyond the visible week. Moving the task will truncate to end of visible week. I am guessing that same thing would happen for a task that extended over the month view.</p><p><br />Created by derry43</p>
<blockquote>GLPI ticket number: <a href='https://xes.ticgal.com/index.php?redirect=ticket_7105' rel='nofollow'>7105</a><br/>Created with <a href='https://tic.gal'>GitSync</a> in GLPI by Óscar Beiro</blockquote>

**Comment by derry43** [comment]
GLPI 9.5.4, taskdrop 1.2.0

**Comment by OscarBeiro** [comment]
Hi Derry,
There is some misunderstanding here.
For the time being, we only deal with not-scheduled Ticket tasks and reminders.
If you are asking for an enhancement, (Supporting Project Tasks) we can send you a proposal.

Any other bug related to GLPI Planning should be reported to the GLPI project. If you need professional support we can assist with this.

Cheers,
